services:
  wechat:
#    image: ricwang/docker-wechat:latest
    build: ./docker-wechat-main
    container_name: wechat_container
    volumes:
      - ./.xwechat:/root/.xwechat
      - ./xwechat_files:/root/xwechat_files
      - ./downloads:/root/downloads
    ports:
      - "5800:5800"
      - "5900:5900"
    environment:
      - LANG=zh_CN.UTF-8
      - USER_ID=0
      - GROUP_ID=0
      - WEB_AUDIO=1
      - TZ=Asia/Shanghai
    privileged: true